temporal:
  namespaces:
    default:
      workflows:
        client_count: 1
      connection:
        target: localhost:7233
#        api_key: someapikey
#        mtls:
#          cert_chain_file: /path/to/file.pem
#          key_file: /path/to/key.pem
#          key_password: foo123
#          insecure_trust_manager: false
#          server_name: optional
#          server_root_ca_certificate_file: optional
      task_queues:
        default:
          worker_count: 1
          max_cached_workflows: 10000
          capacity:
            max_concurrent_workflow_task_pollers: 2
            max_concurrent_workflow_task_executors: 1000
            max_concurrent_activity_task_pollers: 2
            max_concurrent_activity_task_executors: 1000
            max_concurrent_local_activity_executors: 1000
          rate_limits:
            max_worker_activities_per_second: 0
            max_task_queue_activities_per_second: 0
          tuner:
            target_mem: 0
            target_cpu: 0
  prometheus:
    address: 0.0.0.0:9000
    prefix: temporal_